replicaCount: 1
image:
  repository: ghcr.io/subhamproject/argo-app/main
  pullPolicy: Always
  tag: db44dbc
imagePullSecrets:
  - name: gitsecret
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  enabled: true
  type: NodePort
  port: 9001
  nodePort: 30071
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
hpa:
  enabled: true
  maxReplicas: 10
  cpu: 40
  memory: 40
  requests: 40
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 20m
    memory: 64Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
